### ISSUE TITLE
Redirecting output of winpty to file

### ISSUE THREAD

**Issue by sanguine8082** [rprichard/winpty#100]
I'm calling a python script using winpty; I'd like to do the following:
```bash
winpty /path/to/python script.py | tee output.txt
```

When I try to do this, I receive a message saying "stdout is not a tty".  I'm calling this python script from a mintty console.  Is there anyway to pipe output from winpty's pipe into an output file that I can read?

I have requirements that prevent me from using Cygwin's Python version.  We use a portable version of python that I have to be able to resolve to using a shebang in my script.

**Comment by rprichard** [comment]
This issue reminds me of https://github.com/rprichard/winpty/issues/93.  You might be able to use `-Xallow-non-pty` for now at least.

**Comment by sanguine8082** [comment]
That would be a negative good sir:

```
winpty -Xallow-non-pty ../io.github.winpython/oss/winpython/python-2.7.10.amd64/python.exe ./test.py
Error: unrecognized option: '-Xallow-non-pty'
```

Calling from the git for windows MinTTY Git Bash.

**Comment by rprichard** [comment]
Sorry, I meant `-Xallow-non-tty`.  (tty vs pty)

**Comment by sanguine8082** [comment]
:anguished: 

I've been bamboozled!

It works now; thank you for looking into this.  I really appreciate it.

**Comment by ahridin** [comment]
Add both '-Xallow-non-tty' and '-Xplain' to prevent ASCII escape characters
