### ISSUE TITLE
winpty_agent.exe never exit

### ISSUE THREAD

**Issue by ayoubserti** [rprichard/winpty#107]
Hello,

I try to use winpty library. It look perfect. But I found that winpty_agent.exe doesn't exit when the spawn'd process exits. 

Is it  a bug or maybe I miss somthing!

**Comment by rprichard** [comment]
By default, the agent doesn't exit until `winpty_free` is called.  That function deallocates the small amount of memory `winpty.dll` uses for each `winpty_t*` instance.  It also closes some handles (e.g. pipe handles), and when `winpty-agent.exe` sees the broken pipe handles, it exits.

There are two flags that change this a bit, `WINPTY_SPAWN_FLAG_AUTO_SHUTDOWN` and `WINPTY_SPAWN_FLAG_EXIT_AFTER_SHUTDOWN`, which [are documented here](https://github.com/rprichard/winpty/blob/6360ec6a5bcdc2c16eba7acc3c2d8e72af605407/src/include/winpty_constants.h#L107).  If *both* flags are set, then the agent will also exit early if the spawned process exits (and once all collected output has been written to the CONOUT/CONERR pipe(s)).  Your code should still call `winpty_free`, though.

e.g. If you're trying to capture all the output from a program, you'd do something like this:

1. Pass the `WINPTY_SPAWN_FLAG_AUTO_SHUTDOWN` flag to `winpty_spawn_config_new`.
2. Get a process handle from `winpty_spawn`.
3. Connect to winpty's CONOUT pipe.
4. Read data until end-of-file on the pipe.
5. Use `GetExitCodeProcess` to get the exit code of the spawned process.
6. Close the process handle and call `winpty_free`.  (Either order is fine.)

**Comment by ayoubserti** [comment]
Thank you @rprichard 

It  works.
