### ISSUE TITLE
fzf etc doesn't automatically return shell.

### ISSUE THREAD

**Issue by erw7** [rprichard/winpty#119]
There is a [report](https://github.com/neovim/neovim/pull/6383#issuecomment-303576813) that it does not automatically return to the shell at the terminal of Neovim at the end of the application using [tcell](https://github.com/gdamore/tcell) such as [fzf](https://github.com/junegunn/fzf) or [micro](https://github.com/zyedidia/micro). They need to enter something from the keyboard to return to the shell. A similar issue also occured in Cygwin's winpty.exe. Therefore, I think that it is a issue of winpty. Or is this a issue with tcell?

* It occurs on Windows 8.1 and 10,  and it dosen't occur on Windows 7.
* Options ```Use legacy console``` are not affected.
* Set the ```WINPTY_SHOW_CONSOLE``` environment variable to 1, exit fzf etc. and click the winpty console to return to the shell.

Can winpty fix this issue?

**Comment by squirrel2038** [comment]
I reproduced the issue with fzf.  It's a bug somewhere in winpty, tcell, and/or fzf, but I don't know what's going on yet.

**Comment by rprichard** [comment]
I reproduced the issue by running fzf.  It's an issue with winpty, tcell, and/or, fzf, but I don't know which.  If the fzf search has completed before I hit Enter/Esc, then I have to hit another key before fzf and winpty exit.  Once they do exit, if I pressed Enter, then the match is displayed.

If the search is still going, then the winpty/fzf immediately exit, and I see the match printed.

**Comment by rprichard** [comment]
I filed https://github.com/gdamore/tcell/issues/158 against tcell.  It's possible to (somewhat) reproduce the problem in an ordinary console without winpty:

In an ordinary console, open `fzf` and wait for it to finish scanning files.  Then do one of:

1. Press Enter and hold it down.  The instant you depress Enter, the screen clears.  `fzf` doesn't print the matched filename until either (a) you release Enter, or (b) the Enter key starts repeating.

2. Open Notepad, press Enter a few times to generate blank lines.  Copy and paste exactly one newline into the clipboard.  (e.g. Ctrl-Home, Shift-Down, Ctrl-C).  Paste this newline into the `fzf` console.  `fzf` will behave exactly as it does with winpty -- i.e. the screen clears and waits for more console input.

Maybe winpty could work around the issue by delaying keyboard input (e.g. when writing multiple `INPUT_RECORD` values, hold the final record in a queue for 1-20ms before writing it).  Right now, I think it's a bad idea -- other programs might prefer the faster input, and it adds complexity.

**Comment by mikesmiffy128** [comment]
gdamore/tcell#158 is fixed which means this issue can probably get closed too.

**Comment by erw7** [comment]
I built fzf using the fixed tcell and confirmed that the problem was solved.
Thank you @rprichard and @mikesmiffy128 .
