### ISSUE TITLE
Random IO errors on write to terminal in Atom/VS Code, caused by a Windows 10 bug

### ISSUE THREAD

**Issue by segevfiner** [rprichard/winpty#134]
I, and others, have been getting weird IO errors/exceptions from Python using embedded terminal implementations in Atom and VS Code. Specifically [platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) and the builtin embedded terminal of VS Code.

The errors are random, running something like this from a Python interpreter should reproduce the error:
```py
for num in xrange(0, 1000):
    print num
```

The error/exception that you get randomly is (Randomly intermingled with output, of course):
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IOError: [Errno 0] Error
```

Essentially it's a `WriteFile`/`write`/`fwrite` call that fails with an errno 0, which should never happen. Which makes it all the more likely that it's winpty, considering that winpty uses hooks to get its job done. (Thank you again, M$ Windows, for having no sane pty-like API).

## Issues
https://github.com/platformio/platformio-atom-ide-terminal/issues/422
https://github.com/Microsoft/vscode/issues/40199
https://github.com/platformio/platformio-vscode-ide/issues/61

cc @rprichard @ivankravets @Tyriar

**Comment by rprichard** [comment]
Thanks for filing this.

> Which makes it all the more likely that it's winpty, considering that winpty uses hooks to get its job done.

FWIW, winpty doesn't really use "hooks". The interesting things that winpty does are:
 - It has a process that's always running in the background of a console, `winpty-agent.exe`.
 - It screen-scrapes the 2D console buffer and looks for changes.
 - When it's looking for changes, it "freezes" application writes to the console by selecting some text. While it's frozen, it sometimes writes a "marker" into the hidden console history so it can track how many times the console buffer has been scrolled. (If it didn't do this, it could still show you the 2D content of the visible console window, but you'd have no scrollback in your terminal. Once a line had scrolled up, it'd be gone.)

I wonder if Windows changed the behavior of writes when text is selected.

I'll need to hunt down that version of Windows and test it.

**Comment by segevfiner** [comment]
@rprichard Must have confused winpty with something else that I remembered used hooks for this 😛

I'm on Windows 10.0.16299.125 x64. This is what you get if you install Windows 10 x64 and update it to the latest update ATM.

**Comment by rprichard** [comment]
> I wonder if Windows changed the behavior of writes when text is selected.

They did, and it looks accidental. I filed this issue: https://github.com/Microsoft/console/issues/40.

**Comment by segevfiner** [comment]
This was fixed in Windows 10 version 1803 (https://github.com/Microsoft/vscode/issues/36630). @rprichard https://github.com/Microsoft/console/issues/40 can probably be closed as well.
