### ISSUE TITLE
terminal screen is cut when window resize 

### ISSUE THREAD

**Issue by Yang09701194** [rprichard/winpty#141]
I have an issue at vscode about **`terminal screen is cut when window resize`** here: **Microsoft/vscode#44894**,

and vscode team reply:

> Nothing we can do about this atm as it's how https://github.com/rprichard/winpty works

<br/>
Could this issue be fixed?  Thank you.

**Comment by rprichard** [comment]
winpty is doing the same thing as an ordinary Windows console here, so I don't think there's anything that can be improved.
