### ISSUE TITLE
Wrong compiler-check in configure script?

### ISSUE THREAD

**Issue by prumand** [rprichard/winpty#144]
I'm trying to compile winpty for and in cygwin (btw. for the docker `-it` flag), but I got the following error:
```
$ ./configure
uname -s identifies a Cygwin environment.
uname -m identifies an x86_64 environment.
Error: could not find Cygwin/MSYS G++ compiler.  One of these should be in your PATH:
 * x86_64-pc-cygwin-g++
```

According to the README.md https://github.com/rprichard/winpty/blame/master/README.md#L53 x86_64-w64-mingw32-g++ should be chosen, but in the configure script it checks for `x86_64-pc-cygwin-g++` https://github.com/rprichard/winpty/blob/master/configure#L71

After Changing this line the configure step worked. Not sure about the details though. Only my second day using windows.

**Comment by k-takata** [comment]
winpty requires two types of GCC: `x86_64-pc-cygwin-g++` and `x86_64-w64-mingw32-g++`.
You also need to install the `gcc-g++` package as the `README.md` says.

**Comment by prumand** [comment]
Ok thx. I misunderstood that then.
