### ISSUE TITLE
Suggestion: winpty WSL PTY support

### ISSUE THREAD

**Issue by lars18th** [rprichard/winpty#148]
Hi @rprichard ,

After reading about `inverted-wslbridge.exe` at https://github.com/mintty/wsltty/issues/41#issuecomment-305063366 ,
I request why the `winpty` tool can't implement WSL PTY support (aka "WSL winpty adapter").

I like to use the WSL shell as my regular terminal in Windows, for both Windows and WSL Linux command tools. At time, using the `wslbridge` I can open the WSL shell in any Terminal (CMD, Cygterm, SSHd, etc.). However, I can't execute the `winpty` from it for the known error of `stdin is not a tty`. So the only solution to run standard _interactive_ console Windows tools from the WSL shell is, as I see it, to implement the WSL PTY support in `winpty`.

Please, can you consider this enhancement?
Thank you!

Note: Regarding the idea of accessing to Win32 name pipes from WSL, the project `npiperelay`does it (using go):
https://github.com/jstarks/npiperelay
https://github.com/tprasadtp/npiperelay

**Comment by rprichard** [comment]
In principle, I think you could ssh from WSL into a Cygwin SSHD, then run winpty.exe from there.

It looks like Microsoft is improving their console/pty/terminal subsystem, and hopefully in the future, the winpty and wslbridge projects won't be needed anymore. See https://github.com/Microsoft/console/issues/57. It looks like the `cmd.exe` shell can run inside a WSL Gnome Terminal.

> I request why the winpty tool can't implement WSL PTY support (aka "WSL winpty adapter").

I probably *could*, but I'm not that motivated to work on this.

**Comment by lars18th** [comment]
Hi @rprichard ,

I'll close this issue as the real solution is to implement support for ConPTY API, as described in #152.

I hope you will support it soon. :wink: 
Regards.
