### ISSUE TITLE
Error: Not found in PATH

### ISSUE THREAD

**Issue by joselcvarela** [rprichard/winpty#154]
Hi folks,
When I tried to run npm with winpty it warned:
```
winpty: error: cannot start 'npm': Not found in PATH
```

I tried with node and it worked perfectly. But with npm not, neither with npx or npm.cmd/npx.cmd
After some hours of research I couldn't find any solution for my problem.
So I tried every version of latest release (0.4.3) and the problem still persisted.

But now, I went to 0.4.2 release and it worked on first attempt.

So this issue is to alert that some regression happened in code.
My guess is the problem resides on if same command exists in more than one folder in PATH.
In this case I have npm.cmd on c:/users/.../roaming/npm and in c:/program files/.../node

**Comment by myuseringithub** [comment]
I have the same issue for `winpty yarn` -> `winpty: error: cannot start 'yarn': Not found in PATH`

Winpty 0.4.3
Node v10.8.0

😕 Made me research how Bash for Windows, mintty and winpty work.

**Comment by janedbal** [comment]
Does your `winpty echo $PATH` look ok?

**Comment by tomwang1013** [comment]
npm.cmd should help

**Comment by ElvenSpellmaker** [comment]
I've got a similar problem with some commands I have, for example `terraform`:
```
$ echo $PATH
/c/Users/JackBlower/.tfenv/bin:...
$ terraform -v
Terraform v0.12.16
```

```
$ winpty echo $PATH
/c/Users/JackBlower/.tfenv/bin:...
$ winpty terraform
winpty: error: cannot start 'terraform': Not found in PATH
```

**Comment by safizn** [comment]
Switch to WSL or WSL2 will not have to deal with winpty

**Comment by gaoming714** [comment]
```
➜   whereis npm
npm: /d/.../nodejs/npm       /d/.../nodejs/npm.cmd
```

Two files in same folder, some terminal use npm.cmd as npm at first.
So, npm in PATH is npm.cmd.
But winpty can't find npm (it does not think them as same)  

Temporary solutions：
`winpty npm.cmd`

It is said, it is caused by $PATHEXT
.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC

**Comment by Sleepful** [comment]
same issue....

`winpty: error: cannot start 'npm': Not found in PATH`

Runs:

`winpty node --version`
This one does work

`whereis npm`
npm: /c/Program Files/nodejs/npm /c/Program Files/nodejs/npm.cmd

`winpty "/c/Program Files/nodejs/npm"`
winpty: error: cannot start '"C:/Program Files/nodejs/npm"': %1 is not a valid Win32 application. (error 0xc1)

`winpty "/c/Program Files/nodejs/npm.cmd" start`
This one does work

`winpty echo $PATH`
...;C:\Users\username\AppData\Roaming\npm;...


**workaround** is making an alias:

`alias npm='winpty "/c/Program Files/nodejs/npm.cmd"'`

then i can run `npm start`

**Comment by joselcvarela** [comment]
Closing since there are an alias to make it work:
Check above (https://github.com/rprichard/winpty/issues/154#issuecomment-572119931)
