### ISSUE TITLE
Disable colon-fixing

### ISSUE THREAD

**Issue by michaelblyons** [rprichard/winpty#164]
Is there a way to turn off the conversion of `:` to `;`? `Robocopy` is unhappy when I try to use its logging flags.

A flag to `winpty`, an escape sequence to make the `:` literal, or anything else would be welcome.

**Comment by michaelblyons** [comment]
At some point, I discovered that double `/`ing the options let Git-for-Windows' Bash know not to fiddle with the the flags on `robocopy`:

``` sh
robocopy source-dir target-dir //mir //log+:$(cygpath --windows "/y/logs/transfers.log")
```

**Comment by tolomea** [comment]
a solution for other programs would sill be really nice, the one that get's me is pytest which uses :: as a scope delimiter when selecting tests to run
