### ISSUE TITLE
winpty returns the wrong pid

### ISSUE THREAD

**Issue by javruben** [rprichard/winpty#17]
Using pty.js I have found that the pid that is returned is the wrong one (no process with that pid exists - verified using tasklist as well as cygwin's ps)

This is how pty.js uses winpty:
https://github.com/chjj/pty.js/blob/master/src/win/pty.cc#L155

I assume this is a winpty issue. Please let me know otherwise. 

Again, your support is tremendously appreciated.

**Comment by rprichard** [comment]
It's not clear what happened with this issue.  I can reopen if there's still something wrong.

FWIW, my understanding is that pty.js's Windows support isn't currently working, and it also uses a forked version of winpty.  I'm planning on changing the winpty API soon-ish, which should make integrating node.js and winpty much easier.
