### ISSUE TITLE
console.exe cannot handle non-ascii characters in command line argument

### ISSUE THREAD

**Issue by nu774** [rprichard/winpty#20]
console.exe aborts due to assertion failure when I put non-ASCII characters in command line argument.
As far as I can see, it is because mbstowcs() returns -1 since mbstowcs() is locale dependent by spec and requires proper setting of LC_CTYPE via a call to setlocale() for conversion of non-ASCII characters.
In my environment (Cygwin64), the following addition to main() is enough:
```
setlocale(LC_CTYPE, "");
```
As far as I can recall, locale related implementation was poor on Cygwin 1.5 era, so I don't know if it also works for old Cygwin or msys1 as expected.

**Comment by rprichard** [comment]
Fixed by https://github.com/rprichard/winpty/commit/ec385e8d1b25d1e3a20e04947b5d0d1d4c587170.
