### ISSUE TITLE
Can't capture the output of help(0) in a python console

### ISSUE THREAD

**Issue by jchain** [rprichard/winpty#23]
I saw this issue in an IronPython prompt of a cygwin session. The cygwin session ran in Mintty. The output of `help(0)` was empty. I could see a very short halt of the prompt but nothing showed. It should print the type information of the int `0`. Other kinds of outputs seemed all right.

Do you have any idea about the causes to that? Thanks.

**Comment by rprichard** [comment]
I think this issue is fixed now?
