### ISSUE TITLE
Can't get winpty working

### ISSUE THREAD

**Issue by shiek** [rprichard/winpty#27]
Hi!

Thank you all for this great tool!

Unfortunately I can't get winpty working:

My OS: Win7 32bit
Latest winpty version: https://github.com/rprichard/winpty/archive/master.zip

## via Cygwin

packages:
``mingw-gcc-g++``
``gcc-g++  (gcc4-g++ is obsolete)``
``make``

	 ~/winpty-master
	$ ./configure
	uname -s identifies a Cygwin environment.
	uname -m identifies a i686 environment.
	Found Cygwin/MSYS G++ compiler: i686-pc-cygwin-g++
	Found 32-bit MinGW G++ compiler: i686-pc-mingw32-g++
	Writing config-unix.mk
	Writing config-mingw.mk

	 ~/winpty-master
	$ make
	cd agent && make
	make[1]: Entering directory '/home/User/winpty-master/agent'
	Compiling EventLoop.cc
	Compiling NamedPipe.cc
	Compiling Agent.cc
	Compiling AgentAssert.cc
	Compiling Terminal.cc
	Compiling Win32Console.cc
	Compiling ConsoleInput.cc
	Compiling ../shared/DebugClient.cc
	Compiling Coord.cc
	Compiling SmallRect.cc
	Compiling main.cc
	Linking ../build/winpty-agent.exe
	make[1]: Leaving directory '/home/User/winpty-master/agent'
	cd libwinpty && make
	make[1]: Entering directory '/home/User/winpty-master/libwinpty'
	Compiling winpty.cc
	winpty.cc: In function ‘void* createNamedPipe(const wstring&, bool)’:
	winpty.cc:142:28: error: ‘FILE_FLAG_FIRST_PIPE_INSTANCE’ was not declared in this scope
	winpty.cc:150:1: warning: control reaches end of non-void function [-Wreturn-type]
	../config.mk:31: recipe for target 'winpty.o' failed
	make[1]: *** [winpty.o] Error 1
	make[1]: Leaving directory '/home/User/winpty-master/libwinpty'
	Makefile:24: recipe for target 'all' failed
	make: *** [all] Error 2

I don't know what to do at this point in Cygwin.

## via MinGW

packages:
``mingw32-make``
``g++``
``msys-dvlpr``
and the ``zlib1.dll`` in ``C:\MinGW\bin`` (source: http://zlib.net/zlib128-dll.zip)

	 ~/winpty-master
	$ ./configure
	uname -s identifies a MSYS environment.
	Found Cygwin/MSYS G++ compiler: i686-pc-msys-g++
	Found 32-bit MinGW G++ compiler: mingw32-g++
	Writing config-unix.mk
	Writing config-mingw.mk

	 ~/winpty-master
	$ make
	cd agent && make
	make[1]: Entering directory `/home/User/winpty-master/agent'
	Compiling EventLoop.cc
	Compiling NamedPipe.cc
	Compiling Agent.cc
	Compiling AgentAssert.cc
	Compiling Terminal.cc
	Compiling Win32Console.cc
	Compiling ConsoleInput.cc
	Compiling ../shared/DebugClient.cc
	Compiling Coord.cc
	Compiling SmallRect.cc
	Compiling main.cc
	Linking ../build/winpty-agent.exe
	make[1]: Leaving directory `/home/User/winpty-master/agent'
	cd libwinpty && make
	make[1]: Entering directory `/home/User/winpty-master/libwinpty'
	Compiling winpty.cc
	Compiling ../shared/DebugClient.cc
	Linking ../build/winpty.dll
	make[1]: Leaving directory `/home/User/winpty-master/libwinpty'
	cd unix-adapter && make
	make[1]: Entering directory `/home/User/winpty-master/unix-adapter'
	Compiling main.cc
	Compiling Shared.cc
	Linking ../build/console.exe
	make[1]: Leaving directory `/home/User/winpty-master/unix-adapter'

Everything fine at this point. But the console.exe doesn't work.
I tried your testcase via mintty and put everything into

	$ ls /usr/local/bin
	console.exe  msys-1.0.dll  winpty.dll  winpty-agent.exe

With the ``msys-1.0.dll``because of:

	$ console
	/usr/local/bin/console.exe: error while loading shared libraries: msys-1.0.dll: cannot open shared object file: No such file or directory

If I try 

	$ console /cygdrive/c/Python27/python.exe

it just hangs and I have to kill it.

(Python source: https://www.python.org/ftp/python/2.7.8/python-2.7.8.msi)

**Comment by rprichard** [comment]
I added `make` to the Cygwin and MSYS2 package lists in the README.

I think I'll upload new binaries at some point.  The ones at https://github.com/rprichard/winpty/downloads are a few years old now, assume 32 bits, and lack various bugfixes.  (They break badly on Windows 10.)  Issue https://github.com/rprichard/winpty/issues/32 covers that, though.

The `FILE_FLAG_FIRST_PIPE_INSTANCE` bug was fixed in the `winbase.h` header, http://sourceforge.net/p/mingw/bugs/2050/.  If I remove my hack, my code compiles fine with:

 * MSYS1/MinGW (installed using mingw-get)
 * MSYS2 (installed via https://msys2.github.io/ and pacman)
 * MinGW-w64 in Cygwin

It still fails using the original MinGW installed via Cygwin.  Maybe no one is updating its w32api package?  In any case, I changed the `configure` script to prefer MinGW-w64 over MinGW for Cygwin.
