### ISSUE TITLE
Doesn't work with CreateConsoleScreenBuffer/SetConsoleActiveScreenBuffer

### ISSUE THREAD

**Issue by k-takata** [rprichard/winpty#34]
If a program uses `CreateConsoleScreenBuffer()` and `SetConsoleActiveScreenBuffer()`, it doesn't work on winpty.

Here is a sample: https://gist.github.com/k-takata/4564ae4deca758420514

**Comment by k-takata** [comment]
[Vim 7.4.851](https://github.com/vim/vim/commit/615942452eb74eee7d8386fd3d76a1534181fa06) and later doesn't work on winpty anymore, because it uses `CreateConsoleScreenBuffer()` and `SetConsoleActiveScreenBuffer()`.

**Comment by rprichard** [comment]
This issue isn't fixed on Windows 7.  I think it's only fixed on later versions.

**Comment by rprichard** [comment]
i.e. See issue #42.
