### ISSUE TITLE
Some Windows 10 PowerShell text is invisible

### ISSUE THREAD

**Issue by rprichard** [rprichard/winpty#39]
Open Windows 10 PowerShell under winpty with WINPTY_SHOW_CONSOLE=1, and type the text `dir -r`.  The `-r` is visible in the Windows console window, but it is invisible in the terminal.  It looks like the color translation is turning the `-r` into black-on-black or something.

**Comment by PMarci** [comment]
Experiencing the same under cygwin/zsh.
Powershell parameters with a `-` completely invisible and highlight in a strange way.
Seeing as this is closed, I'm wondering whether there is some setting or parameter that I could tweak to make it work...
![screenshot_28](https://user-images.githubusercontent.com/22032937/30752906-0a73e816-9fbe-11e7-950f-7e54226fc1a1.png)
