### ISSUE TITLE
Makefile:77: recipe for target 'build/mingw/PrecompiledHeader.h' failed

### ISSUE THREAD

**Issue by two7sclash** [rprichard/winpty#71]
$ ./configure
uname -s identifies a Cygwin environment.
uname -m identifies an i686 environment.
Found Cygwin/MSYS G++ compiler: i686-pc-cygwin-g++
Found MinGW G++ compiler: i686-w64-mingw32-g++
Writing config.mk
Build info: none

$ make install
Copying src/shared/PrecompiledHeader.h to build/mingw/PrecompiledHeader.h
Makefile:77: recipe for target 'build/mingw/PrecompiledHeader.h' failed
make: *** [build/mingw/PrecompiledHeader.h] Error 127

ideas?

**Comment by rprichard** [comment]
I wonder if make somehow isn't creating the `build/mingw` directory.  If you create that directory by hand, does it build?

The `Makefile` has some unfortunately opaque code to create those directories without calling `mkdir` for each C++ file.  Process creation in Windows is slow.  It was intended to reduce build times:
```
.SECONDEXPANSION :

...

build/mingw/PrecompiledHeader.h : src/shared/PrecompiledHeader.h | $$(@D)/.mkdir
	$(info Copying $< to $@)
	@cp $< $@

...

.PRECIOUS : %.mkdir
%.mkdir :
	@mkdir -p $(dir $@)
	@touch $@

```

It should create a `build/mingw/.mkdir` file as well as the directory.

I pushed [a commit](https://github.com/rprichard/winpty/commit/cf380b39bc9d818da32988ff8b04c5c09c466cb7) that changes the build to print a message when it create a directory, which might help with debugging.

**Comment by rprichard** [comment]
If you could run `(./configure && make clean && make -pn install) > winpty_build_log.txt` and place the result in a GitHub gist, that'd be helpful.

**Comment by two7sclash** [comment]
It creates a 0KB `build/mingw/.mkdir` file.

[Here is the gist](https://gist.github.com/two7sclash/869c50b5e31f64c27eb10a1bd01137c2)

Using /usr/bin/make.

Thanks for your speedy reply!

**Comment by rprichard** [comment]
Those commands look good to me.

Apparently you're executing these commands, and it's failing somehow?
```
mkdir -p build/mingw/
touch build/mingw/.mkdir
cp src/shared/PrecompiledHeader.h build/mingw/PrecompiledHeader.h
```
I assume you can run these commands manually, and it works?

Maybe it's a line-ending issue?  Normally my Makefiles have LF endings.  But...  I just tested Cygwin with gmake 4.1 by switching all my Makefiles to CRLF, and it worked fine.  It seems to ignore the CR.

```
rprichard@ATOM-W10 ~/proj/winpty
$ find -name Makefile -o -name '*.mk' | xargs file
./config.mk:                  ASCII text, with CRLF line terminators
./Makefile:                   BSD makefile script, ASCII text, with CRLF line terminators
./src/agent/subdir.mk:        BSD makefile script, ASCII text, with CRLF line terminators
./src/debugserver/subdir.mk:  BSD makefile script, ASCII text, with CRLF line terminators
./src/libwinpty/subdir.mk:    BSD makefile script, ASCII text, with CRLF line terminators
./src/subdir.mk:              ASCII text, with CRLF line terminators
./src/tests/subdir.mk:        BSD makefile script, ASCII text, with CRLF line terminators
./src/unix-adapter/subdir.mk: BSD makefile script, ASCII text, with CRLF line terminators
```

**Comment by two7sclash** [comment]
Turns out there where some permissions issues and the cp commands weren't working. Straightened those out and everything works beautifully!
