### ISSUE TITLE
Unable to build with MSYS2 using provided build instructions

### ISSUE THREAD

**Issue by seishun** [rprichard/winpty#75]
Steps to reproduce:

1. Install msys2-x86_64-20160205, follow the post-installation instructions provided on https://msys2.github.io/
2. Install `msys/gcc`, `mingw64/mingw-w64-x86_64-gcc` and `make`
3. Try to run `./configure`:

```
Nikolai@DESKTOP-BF4LIO9 MSYS /c/Users/Nikolai/Downloads/winpty
$ ./configure
uname -s identifies an MSYS/MSYS2 environment.
uname -m identifies an x86_64 environment.
Found Cygwin/MSYS G++ compiler: x86_64-pc-msys-g++
Error: could not find MinGW G++ compiler.  One of these should be in your PATH:
 * x86_64-w64-mingw32-g++
```

**Comment by seishun** [comment]
Adding `/mingw64/bin` to PATH fixed the issue for me. Is that the proper way?

**Comment by rprichard** [comment]
IIRC, there are separate Windows shortcuts for launching an MSYS shell versus a MinGW shell.  You'll need the MinGW shell.  If adding `/mingw64/bin` to the PATH works, though, that's fine.

There's also a `winpty` package for MSYS2 that you could install with `pacman`.

**Comment by seishun** [comment]
Indeed, when using "MinGW-w64 Win64 Shell", `./configure` works without modifying PATH. Perhaps this should be mentioned in the README?

**Comment by rprichard** [comment]
I suppose the README could mention using the MinGW-w64 shell shortcut.  I wonder if installing both the 32-bit and 64-bit MinGW compilers produces two MinGW-w64 shell shortcuts, one per architecture.  It would be necessary to use the one whose architecture matched that of the MSYS2 installation.

**Comment by seishun** [comment]
Installing the compilers doesn't add any shortcuts. After installing just MSYS2 64-bit, I had the following shortcuts under MSYS2:

* MinGW-w64 Win32 Shell
* MinGW-w64 Win64 Shell
* MSYS2 Shell

I had to use the second one, the first one gives the same error as the last one.

**Comment by equalsraf** [comment]
For clarification MSYS2 offers three distinct environments, choose the one that fits your target

1. MSYS2 Shell - similar to cygwin produces binaries that link against the MSYS dll, and has a compatibility layer that allows UNIX code to run on windows (e.g. UNIX paths or termiios.h are fair game). This is under /usr.
2. MinGW-w64 Win64 Shell uses native 64 bit Windows binaries that only link against the Windows runtime. This is under /mingw64.
3. MinGW-w64 Win32 Shell, similar to the previous one but for 32bit binaries. This is under /mingw32

Notice that the packages are not the same for all three. For native x86_64 the package names start with mingw-w64-x86_64, and packages are only available under the matching environment (unless you override the PATH :D).

**Comment by rprichard** [comment]
I added a extra note about MSYS2.  It's also possible to use the `mingw-w64-cross-gcc` package (which is what the official MSYS2 `winpty` and `winpty-git` packages use), so I added that as an alternative.

**Comment by liudonghua123** [comment]
I use `mingw32.exe` and also have installed `mingw-w64-i686-gcc`, `mingw-w64-cross-gcc` and `mingw-w64-cross-crt-git` packages, but when I execute configure
```bash
Liu.D.H@desktop-ldh MINGW32 ~/code/winpty$ gcc -v
Using built-in specs.
COLLECT_GCC=C:\msys32\mingw32\bin\gcc.exe
COLLECT_LTO_WRAPPER=C:/msys32/mingw32/bin/../lib/gcc/i686-w64-mingw32/7.3.0/lto-wrapper.exe
Target: i686-w64-mingw32
Configured with: ../gcc-7.3.0/configure --prefix=/mingw32 --with-local-prefix=/mingw32/local --build=i686-w64-mingw32 --host=i686-w64-mingw32 --target=i686-w64-mingw32 --with-native-system-header-dir=/mingw32/i686-w64-mingw32/include --libexecdir=/mingw32/lib --enable-bootstrap --with-arch=i686 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --enable-libstdcxx-filesystem-ts=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw32 --with-mpfr=/mingw32 --with-mpc=/mingw32 --with-isl=/mingw32 --with-pkgversion='Rev2, Built by MSYS2 project' --with-bugurl=https://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld --disable-sjlj-exceptions --with-dwarf2
Thread model: posix
gcc version 7.3.0 (Rev2, Built by MSYS2 project)
Liu.D.H@desktop-ldh MINGW32 ~/code/winpty$ i686-
i686-pc-msys-pkg-config.exe      i686-w64-mingw32-gcc-7.3.0.exe   i686-w64-mingw32-pkg-config.exe
i686-w64-mingw32-agrep.exe       i686-w64-mingw32-gcc-ar.exe      i686-w64-mingw32-reset.exe
i686-w64-mingw32-c++.exe         i686-w64-mingw32-gcc-nm.exe      i686-w64-mingw32-tabs.exe
i686-w64-mingw32-captoinfo.exe   i686-w64-mingw32-gcc-ranlib.exe  i686-w64-mingw32-tic.exe
i686-w64-mingw32-clear.exe       i686-w64-mingw32-gfortran.exe    i686-w64-mingw32-toe.exe
i686-w64-mingw32-deflatehd.exe   i686-w64-mingw32-inflatehd.exe   i686-w64-mingw32-tput.exe
i686-w64-mingw32-g++.exe         i686-w64-mingw32-infocmp.exe     i686-w64-mingw32-tset.exe
i686-w64-mingw32-gcc.exe         i686-w64-mingw32-infotocap.exe
Liu.D.H@desktop-ldh MINGW32 ~/code/winpty$ ./configure
uname -s identifies an MSYS/MSYS2 environment.
uname -m identifies an i686 environment.
Error: could not find Cygwin/MSYS G++ compiler.  One of these should be in your PATH:
 * i686-pc-msys-g++
Liu.D.H@desktop-ldh MINGW32 ~/code/winpty$

```

**Comment by k-takata** [comment]
Maybe you forgot to install `msys/gcc` package.

**Comment by liudonghua123** [comment]
@k-takata Thanks, now it's works. Could you tell me what's the difference between `msys/gcc` and `mingw-w64-i686-gcc` and `mingw-w64-cross-gcc`.

**Comment by k-takata** [comment]
`msys/gcc` is targeting msys2 platform, the compiled program requires `msys-2.0.dll`.

Both `mingw-w64-i686-gcc` and `mingw-w64-cross-gcc` are targeting Win32 platform, the compiled program doesn't need `msys-2.0.dll`. One of the differences is that the former is targeting only 32-bit Win32 and the latter is targeting both 64- and 32-bit Win32. Another difference is that `mingw-w64-cross-gcc` itself requires `msys-2.0.dll`.
