### ISSUE TITLE
Provide more informative error messages 

### ISSUE THREAD

**Issue by gene-pavlovsky** [rprichard/winpty#76]
I was doing this

```
# winpty far
Error 0x2 starting far
```

It tooks some digging to figure out what was wrong. Basically, `far` was not in my PATH (I erroneously assumed it is). I thought the problem was in far itself. If winpty provided a full error message instead of just error code, I would definitely be able to figure it out sooner: `Error 0x2 starting far -- The system cannot find the file specified.` is much more obvious.

**Comment by rprichard** [comment]
It should now print a message like this:
```
# winpty far
Could not start 'far': The system cannot find the file specified. (error 0x2)
```

**Comment by gene-pavlovsky** [comment]
Thanks!
