### ISSUE TITLE
Windows 10 VS2015 Compile Errors

### ISSUE THREAD

**Issue by download13** [rprichard/winpty#87]
I got these errors trying to build a dependant npm package on Windows 10 using VS2015.

According to [stackoverflow](http://stackoverflow.com/questions/19439670/min-max-not-a-member-of-std-errors-when-building-opencv-2-4-6-on-windows-8) the `min` and `max` errors can be solved by `#include`ing `algorithm`.

The problem with CSI seems to be a symptom of [some changes in C++11](http://stackoverflow.com/questions/31738796/using-macro-with-string-fails-on-vc-2015).

```
Building the projects in this solution one at a time. To enable parallel build,                                                                         please add the "/m" switch.
  Agent.cc
  AgentAssert.cc
  ConsoleInput.cc
  Coord.cc
  EventLoop.cc
  NamedPipe.cc
  SmallRect.cc
  Terminal.cc
  Win32Console.cc
..\..\..\deps\winpty\agent\EventLoop.cc(69): error C2039: 'max': is not a member of 'std' [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\EventLoop.cc(69): error C3861: 'max': identifier not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  main.cc
  DebugClient.cc
..\..\..\deps\winpty\agent\Terminal.cc(60): error C3688: invalid literal suffix 'CSI'; literal operator or literal operator template 'operator ""CSI' not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(165): error C3688: invalid literal suffix 'CSI'; literal operator or literal operator template 'operator ""CSI' not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(165): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot convert argument 2 from 'int' to 'const char *const ' [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  ..\..\..\deps\winpty\agent\Terminal.cc(165): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\..\..\deps\winpty\agent\Terminal.cc(190): error C3688: invalid literal suffix 'CSI'; literal operator or literal operator template 'operator ""CSI' not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\Terminal.cc(190): error C2664: 'int sprintf(char *const ,const char *const ,...)': cannot convert argument 2 from 'int' to 'const char *const ' [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  ..\..\..\deps\winpty\agent\Terminal.cc(190): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
..\..\..\deps\winpty\agent\NamedPipe.cc(153): error C2039: 'min': is not a member of 'std' [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\NamedPipe.cc(153): error C3861: 'min': identifier not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(222): error C2039: 'min': is not a member of 'std' [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\NamedPipe.cc(222): error C3861: 'min': identifier not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C2039: 'min': is not a member of 'std' [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C3861: 'min': identifier not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  winpty.cc
  DebugClient.cc
..\..\..\deps\winpty\libwinpty\winpty.cc(139): error C3688: invalid literal suffix 'AGENT_EXE'; literal operator or literal operator template 'operator ""AGENT_EXE' not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty.vcxproj]
```

..\..\..\deps\winpty\agent\NamedPipe.cc(222): error C3861: 'min': identifier not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C2039: 'min': is not a member of 'std' [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(17): note: see declaration of 'std'
..\..\..\deps\winpty\agent\NamedPipe.cc(229): error C3861: 'min': identifier not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty-agent.vcxproj]
  winpty.cc
  DebugClient.cc
..\..\..\deps\winpty\libwinpty\winpty.cc(139): error C3688: invalid literal suffix 'AGENT_EXE'; literal operator or literal operator template 'operator ""AGENT_EXE' not found [C:\Users\download\Desktop\black-screen\node_modules\pty.js\build\deps\winpty\winpty.vcxproj]
```

**Comment by rprichard** [comment]
Those build problems were fixed in this repository in October 2015.  You must be using an npm package whose winpty dependency is out-of-date (e.g. https://github.com/chjj/pty.js).

The original winpty API wasn't appropriate for pty.js, so pty.js modified it.  That makes sense, but it also makes updating harder.  Within the past few months, I released a new winpty version (0.4.0) with a new API that should be good enough out-of-the-box.  However, pty.js would need adaptation.

To my knowledge, VSCode has a forked version of pty.js that compiles (https://github.com/Microsoft/vscode/blob/0421a3492317a4ca1adaa7f3513391d312cb10c3/package.json#L27, https://github.com/Tyriar/pty.js).  Assuming you aren't interested in working on pty.js, that's probably your best option.

**Comment by rprichard** [comment]
I think these two commits are the relevant ones:

 - string literals: https://github.com/rprichard/winpty/commit/bde8922e08c3638e01ecc7b581b676c314163e3c
 - `<algorithm>`: https://github.com/rprichard/winpty/commit/195cf0aec5357ff2e2748bf4e078b3f7bbe212a1

**Comment by download13** [comment]
Thanks! That's very helpful!
