### ISSUE TITLE
Add an option to pass through input unmodified for WSL mode

### ISSUE THREAD

**Issue by rprichard** [rprichard/winpty#89]
See https://github.com/rprichard/winpty/issues/82#issuecomment-239360693.

**Comment by mintty** [comment]
Thanks a lot for handling this issue.
Passing `--mouse` to winpty would not be a problem in a preconfigured WSL package to solve https://github.com/mintty/mintty/issues/558, but I wonder whether it would be needed because once escape sequences pass through, mouse sequences would be handled alike; we'll see.
[back in 10 days]

**Comment by rprichard** [comment]
The input escape sequences (e.g. mouse movements, button presses/releases) would go through fine, but the output sequences (e.g. enable/disable mouse mode) still wouldn't get through, so mintty would presumably handle mouse input by selecting text, rather than sending mouse escapes to the terminal program.

The `--mouse` option instructs winpty to output escape sequences to enable mouse mode.  Ultimately, it forces winpty to output the escapes [here](https://github.com/rprichard/winpty/blob/6c994460a35cf144c00ae5819a10394c8c7be994/src/agent/Terminal.cc#L495).

Maybe `--mouse` could work for a preconfigured WSL package, but I think it'd require users to decide between mouse-mode and text-selection-mode before starting a WSL program.

**Comment by rprichard** [comment]
I think this approach won't be able to handle the DECCKM mode, where the arrow keys generate an `\eO` prefix rather than `\e[`.  Because winpty is scraping the output buffer, it wouldn't propagate the `\e[?1h` string that switches the mode, so the terminal would continue to send normal input.  So far, I know that this breaks Midnight Commander (https://github.com/rprichard/winpty/issues/90).

**Comment by mintty** [comment]
This request is now satisfied by [wslbridge](https://github.com/rprichard/wslbridge/) (many thanks),
so I think this issue can be closed.
