### ISSUE TITLE
winpty-agent reads beyond end of input queue

### ISSUE THREAD

**Issue by melak47** [rprichard/winpty#94]
In winpty/src/agent/NamedPipe.cc, there is this function:
```cpp
size_t NamedPipe::peek(void *data, size_t size)
{
    ASSERT(m_openMode & OpenMode::Reading);
    const auto out = reinterpret_cast<char*>(data);
    const size_t ret = std::min(size, m_inQueue.size());
    std::copy(&m_inQueue[0], &m_inQueue[size], out);
    return ret;
}
```

Shouldn't `&m_inQueue[size]` be `&m_inQueue[ret]` instead?
I noticed this thanks to MSVC's debug iterators complaining (`m_inQueue.size()` was 0, but `size` was 8).

**Comment by rprichard** [comment]
I think you're right about that.  You can submit a PR if you'd like, or I'll fix it tonight probably.

Thanks for the report.
